### ISSUE TITLE
story: upgrade to MK v0.10.4

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/android-libs#60]
Done for the latest stable tag, but not done in master.

List of tasks:

- [x] spring cleaning of open issues to understand what to include into this update (https://github.com/measurement-kit/android-libs/issues/59)

- [x] since the stable branch with the master branch (https://github.com/measurement-kit/android-libs/issues/61, https://github.com/measurement-kit/android-libs/issues/62)

- [x] modify the code to use MK from brew (https://github.com/measurement-kit/android-libs/pull/66)

- [x] cut a first release and publish packages to allow @lorenzoPrimi to make progress (https://github.com/measurement-kit/android-libs/issues/67)

- [x] Make MKCollectorResubmitTask constructor public #68

- [x] Cut v0.10.4-2-android.2 and publish it at BinTray #69

- [x] Some JNI bindings have been lost in #65; see #71

- [x] forward port tests written by @xan in https://github.com/measurement-kit/mkall-java; see #73

- [x] consider whether we want to keep smoke testing and testing as part of the Android build or whether we're fine with just doing testing here

- [x] run smoke tests (https://github.com/measurement-kit/homebrew-measurement-kit/issues/23)

- [x] update the example app (https://github.com/measurement-kit/android-example/issues/13)

- [ ] see what integrating assets entails and decide (https://github.com/measurement-kit/android-libs/issues/64)

- [x] proceed with deprecating and freezing https://github.com/measurement-kit/mkall-java

- [ ] see whether we need creating new issues

**Comment by bassosimone** [comment]
I believe we don't want to keep smoke testing. Rather, we want to start writing a more comprehensive test suite as part of android-libs, where we use some assertions. It's less easy to run tests as part of Android studio than it is to copy binaries on a running simulator and just run them, however, this kind of effort is correct in that makes the codebase more Android-y. As such, I am going to archive the smoke testing repository and I am not going to run smoke tests in the above list.

**Comment by bassosimone** [comment]
With respect to integrating assets, I've written a prototype and @lorenzoPrimi has started looking into it. I guess it makes sense to move forward as specified in #64.

**Comment by bassosimone** [comment]
No new issues seem to be necessary. I'm going to call this process concluded.
